# FROM osrf/ros:humble-desktop
FROM ros:humble-perception

RUN apt-get update && apt-get install -y libeigen3-dev nano git
RUN sudo apt-get install -y cmake libgoogle-glog-dev libgflags-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev libceres-dev
RUN apt-get update && apt-get install -y python3-dev python3-matplotlib python3-numpy python3-psutil python3-tk python3-pip
RUN apt-get install -y ros-humble-topic-tools

RUN apt-get update && apt-get install -y ssh build-essential gcc g++ \
    gdb clang cmake rsync tar python3 && apt-get clean

RUN apt-get update && apt-get upgrade -y && apt-get install -y locales xvfb python3 python3-pip python3-rosdep python3-colcon-common-extensions python3-colcon-core
RUN python3 -m pip install -U python-dotenv pyquaternion
RUN python3 -m pip install -U jpl-rosa==1.0.7
RUN python3 -m pip install -U ollama

ENV ROS2_WS /home/aetherra_ws

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
RUN echo "source $ROS2_WS/install/setup.bash" >> ~/.bashrc
RUN echo "alias build='colcon build --symlink-install && source install/setup.bash'" >> ~/.bashrc
RUN echo "alias start='source install/setup.bash && ros2 launch multiagent_launcher multiagent.launch.py'" >> ~/.bashrc

WORKDIR $ROS2_WS

# # Set the entrypoint
# ENTRYPOINT ["/bin/bash"]
CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && \
    echo \"Run \\`build\\` to build the project and \\`start\\` to launch the multiagent sim nodes.\" && \
    /bin/bash"]
